### PR TITLE
Gather only ansible_os_family

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
You asked about overhead, so maybe this is faster

**Comment by Amirsil** [comment]
I like the idea, might be faster but it also doesn't work

image

btw I like your projects on github, great work!

**Comment by Amirsil** [comment]
In order to make it faster now, I added ```gather_subset: facter``` to the playbook
let me know if you find a better working way

**Comment by ghost** [comment]
Oh cool.
I guess we can change the filter to be inside pre_tasks. maybe you have alot of forks and it doesn't really execute it first.

**Comment by ghost** [comment]
Check if it works for you now when it's in pre_tasks

**Comment by Amirsil** [comment]
Good idea, with ```gather_subset``` I have still managed to Optimize by roughly 80%

**Comment by ghost** [comment]
I see. If you think it's not needed, then you can close this merge.

**Comment by Amirsil** [comment]
Yeah it still doesn't work lmao

Not sure u saw it before, but I like your WinAPI C/C++ Project, great work

**Comment by ghost** [comment]
lol. I swear to god, it works on our Ansible server!
So close it I guess haha
and thanks

**Pull request closed without merging**
